# Generated by Django 4.2 on 2023-05-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose_amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccinecentre')),
            ],
        ),
    ]
