# Generated by Django 4.2 on 2023-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecentre',
            name='centreid',
            field=models.PositiveIntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinecentre',
            name='dsitrict',
            field=models.CharField(default='Tiruppur', max_length=25),
            preserve_default=False,
        ),
    ]
