# Generated by Django 4.2 on 2023-05-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vaccinecentre_centreid_vaccinecentre_dsitrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinecentre',
            old_name='dsitrict',
            new_name='district',
        ),
    ]
