# Generated by Django 4.2 on 2023-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_vaccinecentre_centreid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='name',
            field=models.CharField(choices=[('Covishield', 'Covishield'), ('Covaxine', 'Covaxine'), ('Sputnik-V', 'Sputnik-V')], max_length=100),
        ),
    ]
