# Generated by Django 4.2 on 2023-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dosage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecentre',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
